export { HeroSection } from './HeroSection'
export { WhyVergeXSection } from './WhyVergeXSection'
export { OurProductsSection } from './OurProductsSection'
export { SocialMediaSection } from './SocialMediaSection'
export { FooterSection } from './FooterSection'
